#  SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#  SPDX-License-Identifier: Apache-2.0
from dataclasses import dataclass

@dataclass
class Record:
    name: str
    unit: str
    avg: float
    min: float | None = ...
    max: float | None = ...
    p1: float | None = ...
    p5: float | None = ...
    p25: float | None = ...
    p50: float | None = ...
    p75: float | None = ...
    p90: float | None = ...
    p95: float | None = ...
    p99: float | None = ...
    std: float | None = ...
    streaming_only: bool = ...
    def to_dict(self) -> dict: ...
