# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

#########################################################
## This file is auto-generated by mkinit. Do not edit. ##
#########################################################
# mkinit flags
__ignore__ = ["logger"]
__submodules__ = [
    "_aiperf_lifecycle",
    "_aiperf_logger",
    "_aiperf_message_handler",
    "_aiperf_profile",
    "_aiperf_task",
    "_async_task_manager",
    "_comms",
    "_event_bus_client",
    "_hooks",
    "_process_health",
    "_progress_tracker_mixin",
]
#########################################################


from aiperf.common.mixins._aiperf_lifecycle import (
    AIPerfLifecycleMixin,
    AIPerfLifeCycleProtocol,
)
from aiperf.common.mixins._aiperf_logger import (
    AIPerfLoggerMixin,
    AIPerfLoggerMixinProtocol,
)
from aiperf.common.mixins._aiperf_message_handler import (
    AIPerfMessageHandlerMixin,
)
from aiperf.common.mixins._aiperf_profile import (
    AIPerfProfileMixin,
)
from aiperf.common.mixins._aiperf_task import (
    AIPerfTaskMixin,
)
from aiperf.common.mixins._async_task_manager import (
    AsyncTaskManagerMixin,
    AsyncTaskManagerProtocol,
)
from aiperf.common.mixins._comms import (
    CommunicationsMixin,
)
from aiperf.common.mixins._event_bus_client import (
    EventBusClientMixin,
)
from aiperf.common.mixins._hooks import (
    HooksMixin,
    supports_hooks,
)
from aiperf.common.mixins._process_health import (
    ProcessHealthMixin,
    ProcessHealthMixinProtocol,
)
from aiperf.common.mixins._progress_tracker_mixin import (
    ProgressTrackerMixin,
)

__all__ = [
    "AIPerfLifeCycleProtocol",
    "AIPerfLifecycleMixin",
    "AIPerfLoggerMixin",
    "AIPerfLoggerMixinProtocol",
    "AIPerfMessageHandlerMixin",
    "AIPerfProfileMixin",
    "AIPerfTaskMixin",
    "AsyncTaskManagerMixin",
    "AsyncTaskManagerProtocol",
    "CommunicationsMixin",
    "EventBusClientMixin",
    "HooksMixin",
    "ProcessHealthMixin",
    "ProcessHealthMixinProtocol",
    "ProgressTrackerMixin",
    "supports_hooks",
]
