#  SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#  SPDX-License-Identifier: Apache-2.0
from collections.abc import AsyncIterator, Iterator

from _typeshed import Incomplete

from aiperf.common.enums import ServiceState as ServiceState
from aiperf.common.enums import ServiceType as ServiceType
from aiperf.common.service_models import (
    ServiceRegistrationInfo as ServiceRegistrationInfo,
)

class ServiceRegistry:
    logger: Incomplete
    def __init__(self) -> None: ...
    def register_service(
        self, service_id: str, service_type: ServiceType, state: ServiceState = ...
    ) -> ServiceRegistrationInfo: ...
    def unregister_service(self, service_id: str) -> bool: ...
    def __contains__(self, service_id: str) -> bool: ...
    def __getitem__(self, service_id: str) -> ServiceRegistrationInfo: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[ServiceRegistrationInfo]: ...
    async def __aiter__(self) -> AsyncIterator[ServiceRegistrationInfo]: ...
    def service_ids_by_type(self, service_type: ServiceType) -> set[str]: ...
    def all_service_types(self) -> set[ServiceType]: ...
    def all_service_ids(self) -> set[str]: ...
    def num_replicas(self, service_type: ServiceType) -> int: ...
    def services_with_state(self, *states: ServiceState) -> set[str]: ...
    def update_service_state(self, service_id: str, state: ServiceState) -> bool: ...
    def update_service_heartbeat(self, service_id: str) -> bool: ...
    def clear(self) -> None: ...

GlobalServiceRegistry: Incomplete
