import asyncio
import json
import logging
import random
import time
import uuid
from typing import Any, Dict, List, Optional, Union

import uvicorn
from fastapi import FastAPI, Request, Response, HTTPException, Depends, Header
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field


# Configure logging
logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger("mock_openai_server")

# Create FastAPI app
app = FastAPI(title="Mock OpenAI API")

# Add CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Mock server settings
SETTINGS = {
    "delay_min": 0.1,  # Minimum delay in seconds
    "delay_max": 1.0,  # Maximum delay in seconds
    "error_rate": 0.0,  # Error rate (0.0 - 1.0)
    "token_rate": 15.0,  # Tokens per second for streaming
}

# In-memory request log
REQUEST_LOG = []


# Model definitions
class Message(BaseModel):
    role: str
    content: str
    name: Optional[str] = None


class ChatCompletionRequest(BaseModel):
    model: str
    messages: List[Message]
    temperature: Optional[float] = 1.0
    top_p: Optional[float] = 1.0
    n: Optional[int] = 1
    stream: Optional[bool] = False
    max_tokens: Optional[int] = None
    presence_penalty: Optional[float] = 0.0
    frequency_penalty: Optional[float] = 0.0
    user: Optional[str] = None


class CompletionRequest(BaseModel):
    model: str
    prompt: Union[str, List[str]]
    temperature: Optional[float] = 1.0
    top_p: Optional[float] = 1.0
    n: Optional[int] = 1
    stream: Optional[bool] = False
    max_tokens: Optional[int] = None
    presence_penalty: Optional[float] = 0.0
    frequency_penalty: Optional[float] = 0.0
    user: Optional[str] = None


# Mock data for responses
MOCK_RESPONSES = {
    "chat": [
        "I'm a mock AI response from the local test server. This is simulating an OpenAI API response. I hope your testing is going well!",
        "Here's another mock response. In a real scenario, this would be generated by GPT but for testing, this pre-written text will do.",
        "Testing is an essential part of development. This mock server helps you test without using real API credits.",
        "This is a simulated response from your local mock OpenAI server. It's working as expected!",
        "Mock servers are useful for testing API integrations without incurring costs or depending on external services.",
    ],
    "completion": [
        "This is a mock completion response. It's simulating the text completion endpoint.",
        "Another mock completion for testing purposes. In production this would be generated by the model.",
        "Automated testing with mock servers can save time and resources during development.",
        "Local development with mock APIs creates a more efficient workflow.",
    ],
}


# Helper functions
async def simulate_delay():
    """Simulate a realistic API delay."""
    delay = random.uniform(SETTINGS["delay_min"], SETTINGS["delay_max"])
    await asyncio.sleep(delay)


def should_error():
    """Determine if this request should return an error based on error rate."""
    return random.random() < SETTINGS["error_rate"]


def generate_mock_response(prompt_type="chat"):
    """Generate a mock response based on the prompt type."""
    return random.choice(MOCK_RESPONSES[prompt_type])


def calculate_tokens(text):
    """Calculate token count (very rough approximation)."""
    # This is a very simple approximation (about 4 chars per token)
    return len(text) // 4


def log_request(endpoint, request_data, response_data):
    """Log request and response for later analysis."""
    REQUEST_LOG.append(
        {
            "timestamp": time.time(),
            "endpoint": endpoint,
            "request": request_data,
            "response": response_data,
        }
    )


# Authentication middleware
async def verify_token(authorization: Optional[str] = Header(None)):
    """Simulate API key verification."""
    if authorization is None:
        # We'll accept missing auth for easier testing
        return "mock_session"

    if not authorization.startswith("Bearer "):
        raise HTTPException(status_code=401, detail="Invalid authentication format")

    # In a real server, we'd validate the token here
    # For mock purposes, we'll accept any token
    token = authorization.replace("Bearer ", "")
    if token == "invalid_token":
        raise HTTPException(status_code=401, detail="Invalid API key")

    return token


# API Endpoints
@app.get("/")
async def root():
    return {"message": "Mock OpenAI API Server", "status": "running"}


@app.get("/v1/models")
async def list_models(token: str = Depends(verify_token)):
    await simulate_delay()

    if should_error():
        raise HTTPException(status_code=500, detail="Simulated server error")

    models = [
        {"id": "gpt-3.5-turbo", "object": "model", "created": 1677610602},
        {"id": "gpt-4", "object": "model", "created": 1687010602},
        {"id": "gpt-4-turbo", "object": "model", "created": 1699910602},
    ]

    response = {"object": "list", "data": models}
    log_request("/v1/models", {}, response)

    return response


@app.post("/v1/chat/completions")
async def create_chat_completion(
    request: ChatCompletionRequest, token: str = Depends(verify_token)
):
    await simulate_delay()

    if should_error():
        raise HTTPException(status_code=500, detail="Simulated server error")

    request_dict = request.dict()

    # If streaming is requested
    if request.stream:
        return Response(
            content=stream_chat_completion(request_dict),
            media_type="text/event-stream",
        )

    # Get a mock response
    mock_content = generate_mock_response("chat")
    input_messages = " ".join([m.content for m in request.messages])

    # Calculate approximate token counts
    prompt_tokens = calculate_tokens(input_messages)
    completion_tokens = calculate_tokens(mock_content)
    total_tokens = prompt_tokens + completion_tokens

    response = {
        "id": f"chatcmpl-{uuid.uuid4().hex}",
        "object": "chat.completion",
        "created": int(time.time()),
        "model": request.model,
        "choices": [
            {
                "index": 0,
                "message": {
                    "role": "assistant",
                    "content": mock_content,
                },
                "finish_reason": "stop",
            }
        ],
        "usage": {
            "prompt_tokens": prompt_tokens,
            "completion_tokens": completion_tokens,
            "total_tokens": total_tokens,
        },
    }

    log_request("/v1/chat/completions", request_dict, response)
    return response


async def stream_chat_completion(request_dict):
    """Generate streaming response for chat completion."""
    model = request_dict.get("model", "gpt-3.5-turbo")
    response_id = f"chatcmpl-{uuid.uuid4().hex}"
    created = int(time.time())

    # Get a mock response
    mock_content = generate_mock_response("chat")

    # Break the response into words
    words = mock_content.split()
    chunk_size = random.randint(1, 3)  # Random number of words per chunk

    # Generate SSE response chunks
    for i in range(0, len(words), chunk_size):
        chunk = " ".join(words[i : i + chunk_size])

        response_chunk = {
            "id": response_id,
            "object": "chat.completion.chunk",
            "created": created,
            "model": model,
            "choices": [
                {
                    "index": 0,
                    "delta": {
                        "content": chunk,
                    },
                    "finish_reason": None,
                }
            ],
        }

        # If this is the last chunk, set finish_reason
        if i + chunk_size >= len(words):
            response_chunk["choices"][0]["finish_reason"] = "stop"

        yield f"data: {json.dumps(response_chunk)}\n\n"

        # Simulate token generation rate
        tokens_in_chunk = calculate_tokens(chunk)
        delay = tokens_in_chunk / SETTINGS["token_rate"]
        await asyncio.sleep(delay)

    # End of stream
    yield "data: [DONE]\n\n"


@app.post("/v1/completions")
async def create_completion(
    request: CompletionRequest, token: str = Depends(verify_token)
):
    await simulate_delay()

    if should_error():
        raise HTTPException(status_code=500, detail="Simulated server error")

    request_dict = request.dict()

    # If streaming is requested
    if request.stream:
        return Response(
            content=stream_completion(request_dict),
            media_type="text/event-stream",
        )

    # Get a mock response
    mock_text = generate_mock_response("completion")
    prompt = (
        request.prompt if isinstance(request.prompt, str) else " ".join(request.prompt)
    )

    # Calculate approximate token counts
    prompt_tokens = calculate_tokens(prompt)
    completion_tokens = calculate_tokens(mock_text)
    total_tokens = prompt_tokens + completion_tokens

    response = {
        "id": f"cmpl-{uuid.uuid4().hex}",
        "object": "text_completion",
        "created": int(time.time()),
        "model": request.model,
        "choices": [
            {
                "text": mock_text,
                "index": 0,
                "logprobs": None,
                "finish_reason": "stop",
            }
        ],
        "usage": {
            "prompt_tokens": prompt_tokens,
            "completion_tokens": completion_tokens,
            "total_tokens": total_tokens,
        },
    }

    log_request("/v1/completions", request_dict, response)
    return response


async def stream_completion(request_dict):
    """Generate streaming response for text completion."""
    model = request_dict.get("model", "text-davinci-003")
    response_id = f"cmpl-{uuid.uuid4().hex}"
    created = int(time.time())

    # Get a mock response
    mock_text = generate_mock_response("completion")

    # Break the response into words
    words = mock_text.split()
    chunk_size = random.randint(1, 3)  # Random number of words per chunk

    # Generate SSE response chunks
    for i in range(0, len(words), chunk_size):
        chunk = " ".join(words[i : i + chunk_size])

        response_chunk = {
            "id": response_id,
            "object": "text_completion",
            "created": created,
            "model": model,
            "choices": [
                {
                    "text": chunk,
                    "index": 0,
                    "logprobs": None,
                    "finish_reason": None,
                }
            ],
        }

        # If this is the last chunk, set finish_reason
        if i + chunk_size >= len(words):
            response_chunk["choices"][0]["finish_reason"] = "stop"

        yield f"data: {json.dumps(response_chunk)}\n\n"

        # Simulate token generation rate
        tokens_in_chunk = calculate_tokens(chunk)
        delay = tokens_in_chunk / SETTINGS["token_rate"]
        await asyncio.sleep(delay)

    # End of stream
    yield "data: [DONE]\n\n"


# Settings management endpoints
@app.get("/mock/settings")
async def get_settings():
    return SETTINGS


@app.post("/mock/settings")
async def update_settings(settings: Dict[str, Any]):
    global SETTINGS
    for key, value in settings.items():
        if key in SETTINGS:
            SETTINGS[key] = value
    return SETTINGS


@app.get("/mock/requests")
async def get_request_log():
    return REQUEST_LOG


@app.post("/mock/clear")
async def clear_request_log():
    global REQUEST_LOG
    REQUEST_LOG = []
    return {"message": "Request log cleared", "status": "success"}


@app.post("/chat/completions")
async def create_chat_completion_no_prefix(
    request: ChatCompletionRequest, token: str = Depends(verify_token)
):
    """Route handler for /chat/completions (without /v1/ prefix)"""
    logger.info(
        "Request received at /chat/completions, redirecting to /v1/chat/completions"
    )
    return await create_chat_completion(request, token)


@app.post("/completions")
async def create_completion_no_prefix(
    request: CompletionRequest, token: str = Depends(verify_token)
):
    """Route handler for /completions (without /v1/ prefix)"""
    logger.info("Request received at /completions, redirecting to /v1/completions")
    return await create_completion(request, token)


if __name__ == "__main__":
    logger.info("Starting Mock OpenAI API Server...")
    uvicorn.run(app, host="0.0.0.0", port=8000)
