# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

########################################################################
## 🚩                     mkinit flags                             🚩 ##
########################################################################
__ignore__ = []
########################################################################
## ⚠️        This file is auto-generated by mkinit                 ⚠️ ##
## ⚠️             Do not edit below this line                      ⚠️ ##
########################################################################

from aiperf.common.messages.commands import (
    CommandMessage,
    CommandResponseMessage,
    ProcessRecordsCommand,
    ProfileCancelCommand,
    ProfileConfigureCommand,
    ProfileStartCommand,
    ProfileStopCommand,
    ShutdownCommand,
    StartWorkersCommand,
    StartWorkersData,
    StopWorkersCommand,
    StopWorkersData,
)
from aiperf.common.messages.credit_messages import (
    CreditDropMessage,
    CreditPhaseCompleteMessage,
    CreditPhaseProgressMessage,
    CreditPhaseSendingCompleteMessage,
    CreditPhaseStartMessage,
    CreditReturnMessage,
    CreditsCompleteMessage,
    FirstByteReceivedMessage,
)
from aiperf.common.messages.dataset_messages import (
    ConversationRequest,
    ConversationResponse,
    ConversationTurnRequest,
    ConversationTurnResponse,
    DatasetConfiguredNotification,
    DatasetTimingRequest,
    DatasetTimingResponse,
)
from aiperf.common.messages.error_messages import (
    BaseServiceErrorMessage,
    ErrorMessage,
)
from aiperf.common.messages.health_messages import (
    WorkerHealthMessage,
)
from aiperf.common.messages.inference_messages import (
    InferenceResultsMessage,
    ParsedInferenceResultsMessage,
)
from aiperf.common.messages.message import (
    AutoRequestID,
    Message,
    RequiresRequestID,
)
from aiperf.common.messages.records_messages import (
    ProfileResultsMessage,
    RecordsProcessingStatsMessage,
)
from aiperf.common.messages.service_messages import (
    BaseServiceMessage,
    BaseStatusMessage,
    HeartbeatMessage,
    RegistrationMessage,
    StatusMessage,
)

__all__ = [
    "AutoRequestID",
    "BaseServiceErrorMessage",
    "BaseServiceMessage",
    "BaseStatusMessage",
    "CommandMessage",
    "CommandResponseMessage",
    "ConversationRequest",
    "ConversationResponse",
    "ConversationTurnRequest",
    "ConversationTurnResponse",
    "CreditDropMessage",
    "CreditPhaseCompleteMessage",
    "CreditPhaseProgressMessage",
    "CreditPhaseSendingCompleteMessage",
    "CreditPhaseStartMessage",
    "CreditReturnMessage",
    "CreditsCompleteMessage",
    "DatasetConfiguredNotification",
    "DatasetTimingRequest",
    "DatasetTimingResponse",
    "ErrorMessage",
    "FirstByteReceivedMessage",
    "HeartbeatMessage",
    "InferenceResultsMessage",
    "Message",
    "ParsedInferenceResultsMessage",
    "ProcessRecordsCommand",
    "ProfileCancelCommand",
    "ProfileConfigureCommand",
    "ProfileResultsMessage",
    "ProfileStartCommand",
    "ProfileStopCommand",
    "RecordsProcessingStatsMessage",
    "RegistrationMessage",
    "RequiresRequestID",
    "ShutdownCommand",
    "StartWorkersCommand",
    "StartWorkersData",
    "StatusMessage",
    "StopWorkersCommand",
    "StopWorkersData",
    "WorkerHealthMessage",
]
