#  SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#  SPDX-License-Identifier: Apache-2.0
import socket
from dataclasses import dataclass

@dataclass(frozen=True)
class SocketDefaults:
    TCP_NODELAY = ...
    TCP_QUICKACK = ...
    SO_KEEPALIVE = ...
    TCP_KEEPIDLE = ...
    TCP_KEEPINTVL = ...
    TCP_KEEPCNT = ...
    SO_LINGER = ...
    SO_REUSEADDR = ...
    SO_REUSEPORT = ...
    SO_RCVBUF = ...
    SO_SNDBUF = ...
    SO_RCVTIMEO = ...
    SO_SNDTIMEO = ...
    TCP_USER_TIMEOUT = ...
    @classmethod
    def apply_to_socket(cls, sock: socket.socket) -> None: ...

@dataclass(frozen=True)
class AioHttpDefaults:
    LIMIT = ...
    LIMIT_PER_HOST = ...
    TTL_DNS_CACHE = ...
    USE_DNS_CACHE = ...
    ENABLE_CLEANUP_CLOSED = ...
    FORCE_CLOSE = ...
    KEEPALIVE_TIMEOUT = ...
    HAPPY_EYEBALLS_DELAY = ...
    SOCKET_FAMILY = ...
