#  SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#  SPDX-License-Identifier: Apache-2.0
from collections.abc import Callable as Callable

from _typeshed import Incomplete

class AIPerfLogger:
    logger_name: Incomplete
    is_enabled_for: Incomplete
    set_level: Incomplete
    get_effective_level: Incomplete
    isEnabledFor: Incomplete
    setLevel: Incomplete
    getEffectiveLevel: Incomplete
    handlers: Incomplete
    addHandler: Incomplete
    removeHandler: Incomplete
    hasHandlers: Incomplete
    root: Incomplete
    def __init__(self, logger_name: str) -> None: ...
    @classmethod
    def is_valid_level(cls, level: int | str) -> bool: ...
    @classmethod
    def get_level_number(cls, level: int | str) -> int: ...
    def find_caller(
        self, stack_info: bool = False, stacklevel: int = 1
    ) -> tuple[str, int, str, str | None]: ...
    def log(
        self, level: int, msg: str | Callable[..., str], *args, **kwargs
    ) -> None: ...
    def trace(self, msg: str | Callable[..., str], *args, **kwargs) -> None: ...
    def debug(self, msg: str | Callable[..., str], *args, **kwargs) -> None: ...
    def info(self, msg: str | Callable[..., str], *args, **kwargs) -> None: ...
    def notice(self, msg: str | Callable[..., str], *args, **kwargs) -> None: ...
    def warning(self, msg: str | Callable[..., str], *args, **kwargs) -> None: ...
    def success(self, msg: str | Callable[..., str], *args, **kwargs) -> None: ...
    def error(self, msg: str | Callable[..., str], *args, **kwargs) -> None: ...
    def exception(self, msg: str | Callable[..., str], *args, **kwargs) -> None: ...
    def critical(self, msg: str | Callable[..., str], *args, **kwargs) -> None: ...
