#  SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#  SPDX-License-Identifier: Apache-2.0
from _typeshed import Incomplete

NANOS_PER_SECOND: int
NANOS_PER_MILLIS: int
BYTES_PER_MIB: Incomplete
GRACEFUL_SHUTDOWN_TIMEOUT_SECONDS: float
TASK_CANCEL_TIMEOUT_SHORT: float
TASK_CANCEL_TIMEOUT_LONG: float
DEFAULT_COMMS_REQUEST_TIMEOUT: float
DEFAULT_WAIT_FOR_REGISTRATION_SECONDS: float
DEFAULT_WAIT_FOR_START_SECONDS: float
DEFAULT_WAIT_FOR_STOP_SECONDS: float
