#  SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#  SPDX-License-Identifier: Apache-2.0
from _typeshed import Incomplete

from aiperf.common.enums import ServiceType as ServiceType

class AIPerfError(Exception):
    def raw_str(self) -> str: ...

class AIPerfMultiError(AIPerfError):
    exceptions: Incomplete
    def __init__(self, message: str, exceptions: list[Exception]) -> None: ...

class ServiceError(AIPerfError):
    service_type: Incomplete
    service_id: Incomplete
    def __init__(
        self, message: str, service_type: ServiceType, service_id: str
    ) -> None: ...

class InitializationError(AIPerfError): ...
class ConfigurationError(AIPerfError): ...
class NotInitializedError(AIPerfError): ...
class InvalidStateError(AIPerfError): ...
class ValidationError(AIPerfError): ...
class NotFoundError(AIPerfError): ...
class CommunicationError(AIPerfError): ...
class DatasetError(AIPerfError): ...
class DatasetGeneratorError(AIPerfError): ...
class InferenceClientError(AIPerfError): ...
class InvalidPayloadError(InferenceClientError): ...
class UnsupportedHookError(AIPerfError): ...
class FactoryCreationError(AIPerfError): ...
class MetricTypeError(AIPerfError): ...
class ShutdownError(AIPerfError): ...
class ProxyError(AIPerfError): ...
class ServiceTimeoutError(AIPerfError): ...
class PluginError(AIPerfError): ...
class PluginNotFoundError(PluginError): ...
