#  SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#  SPDX-License-Identifier: Apache-2.0
from collections.abc import Callable as Callable

from _typeshed import Incomplete

from aiperf.common.enums import CaseInsensitiveStrEnum as CaseInsensitiveStrEnum
from aiperf.common.enums._message import MessageType as MessageType
from aiperf.common.exceptions import AIPerfError as AIPerfError
from aiperf.common.exceptions import AIPerfMultiError as AIPerfMultiError
from aiperf.common.exceptions import UnsupportedHookError as UnsupportedHookError

class AIPerfHook(CaseInsensitiveStrEnum):
    ON_INIT = "__aiperf_on_init__"
    ON_RUN = "__aiperf_on_run__"
    ON_CONFIGURE = "__aiperf_on_configure__"
    ON_PROFILE_CONFIGURE = "__aiperf_on_profile_configure__"
    ON_PROFILE_START = "__aiperf_on_profile_start__"
    ON_PROFILE_STOP = "__aiperf_on_profile_stop__"
    ON_START = "__aiperf_on_start__"
    ON_STOP = "__aiperf_on_stop__"
    ON_CLEANUP = "__aiperf_on_cleanup__"
    ON_SET_STATE = "__aiperf_on_set_state__"
    ON_MESSAGE = "__aiperf_on_message__"

class AIPerfTaskHook(CaseInsensitiveStrEnum):
    AIPERF_TASK = "__aiperf_task__"
    AIPERF_AUTO_TASK = "__aiperf_auto_task__"

class AIPerfHookParams:
    AIPERF_AUTO_TASK_INTERVAL_SEC: str
    ON_MESSAGE_MESSAGE_TYPES: str

HookType = AIPerfHook | AIPerfTaskHook | str
AIPERF_HOOK_TYPE: str

class HookSystem:
    logger: Incomplete
    supported_hooks: set[HookType]
    def __init__(self, supported_hooks: set[HookType]) -> None: ...
    def register_hook(self, hook_type: HookType, func: Callable): ...
    def get_hooks(self, hook_type: HookType) -> list[Callable]: ...
    async def run_hooks(self, hook_type: HookType, *args, **kwargs): ...
    async def run_hooks_async(self, hook_type: HookType, *args, **kwargs): ...

def hook_decorator(hook_type: HookType, func: Callable) -> Callable: ...
def on_init(func: Callable) -> Callable: ...
def on_start(func: Callable) -> Callable: ...
def on_stop(func: Callable) -> Callable: ...
def on_configure(func: Callable) -> Callable: ...
def on_cleanup(func: Callable) -> Callable: ...
def on_run(func: Callable) -> Callable: ...
def on_set_state(func: Callable) -> Callable: ...
def on_profile_configure(func: Callable) -> Callable: ...
def on_profile_start(func: Callable) -> Callable: ...
def on_profile_stop(func: Callable) -> Callable: ...
def aiperf_task(func: Callable) -> Callable: ...
def aiperf_auto_task(interval_sec: float) -> Callable[[Callable], Callable]: ...
def on_message(*message_types: MessageType) -> Callable: ...
