#  SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#  SPDX-License-Identifier: Apache-2.0
from transformers import BatchEncoding as BatchEncoding

from aiperf.common.exceptions import InitializationError as InitializationError
from aiperf.common.exceptions import NotInitializedError as NotInitializedError

class Tokenizer:
    def __init__(self) -> None: ...
    @classmethod
    def from_pretrained(
        cls, name: str, trust_remote_code: bool = False, revision: str = "main"
    ) -> Tokenizer: ...
    def __call__(self, text, **kwargs) -> BatchEncoding: ...
    def encode(self, text, **kwargs) -> list[int]: ...
    def decode(self, token_ids, **kwargs) -> str: ...
    @property
    def bos_token_id(self) -> int: ...
