#  SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#  SPDX-License-Identifier: Apache-2.0
from collections.abc import Callable as Callable
from typing import Any

from _typeshed import Incomplete

from aiperf.common import aiperf_logger as aiperf_logger
from aiperf.common.exceptions import AIPerfError as AIPerfError
from aiperf.common.exceptions import AIPerfMultiError as AIPerfMultiError

logger: Incomplete

async def call_all_functions_self(
    self_: object, funcs: list[Callable], *args, **kwargs
) -> None: ...
async def call_all_functions(funcs: list[Callable], *args, **kwargs) -> None: ...
def sample_bounded_normal(
    mean: float, stddev: float, lower: float = ..., upper: float = ...
) -> float: ...
def sample_bounded_normal_int(
    mean: float, stddev: float, lower: float = ..., upper: float = ...
) -> int: ...
def load_json_str(json_str: str, func: Callable = ...) -> dict[str, Any]: ...
def format_duration(seconds: float | None, none_str: str = "--") -> str: ...
def format_bytes(bytes: int | None, none_str: str = "--") -> str: ...
