# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

########################################################################
## 🚩                     mkinit flags                             🚩 ##
########################################################################
__ignore__ = []
########################################################################
## ⚠️        This file is auto-generated by mkinit                 ⚠️ ##
## ⚠️             Do not edit below this line                      ⚠️ ##
########################################################################
from aiperf.common.enums.base_enums import (
    CaseInsensitiveStrEnum,
)
from aiperf.common.enums.benchmark_enums import (
    BenchmarkSuiteCompletionTrigger,
    BenchmarkSuiteType,
    ProfileCompletionTrigger,
)
from aiperf.common.enums.communication_enums import (
    CommunicationBackend,
    CommunicationClientAddressType,
    CommunicationClientType,
    ZMQProxyType,
)
from aiperf.common.enums.data_exporter_enums import (
    DataExporterType,
)
from aiperf.common.enums.dataset_enums import (
    AudioFormat,
    ComposerType,
    CustomDatasetType,
    ImageFormat,
    PromptSource,
)
from aiperf.common.enums.endpoints_enums import (
    EndpointType,
    ResponsePayloadType,
)
from aiperf.common.enums.logging_enums import (
    AIPerfLogLevel,
)
from aiperf.common.enums.measurement_enums import (
    MeasurementMode,
)
from aiperf.common.enums.message_enums import (
    CommandMessageType,
    CommandResponseMessageType,
    CreditMessageType,
    DatasetMessageType,
    ErrorMessageType,
    InferenceMessageType,
    MessageType,
    ProfileMessageType,
    SweepMessageType,
    SystemMessageType,
    TestMessageType,
    WorkerMessageType,
)
from aiperf.common.enums.metric_enums import (
    MetricTimeType,
    MetricType,
)
from aiperf.common.enums.model_enums import (
    Modality,
    ModelSelectionStrategy,
)
from aiperf.common.enums.post_processor_enums import (
    PostProcessorType,
    StreamingPostProcessorType,
)
from aiperf.common.enums.service_enums import (
    ServiceRegistrationStatus,
    ServiceRunType,
    ServiceState,
    ServiceType,
)
from aiperf.common.enums.sse_enums import (
    SSEEventType,
    SSEFieldType,
)
from aiperf.common.enums.system_enums import (
    SystemState,
)
from aiperf.common.enums.timing_enums import (
    CreditPhase,
    RequestRateMode,
    TimingMode,
)
from aiperf.common.enums.ui_enums import (
    AIPerfUIType,
)

__all__ = [
    "AIPerfLogLevel",
    "AIPerfUIType",
    "AudioFormat",
    "BenchmarkSuiteCompletionTrigger",
    "BenchmarkSuiteType",
    "CaseInsensitiveStrEnum",
    "CommandMessageType",
    "CommandResponseMessageType",
    "CommunicationBackend",
    "CommunicationClientAddressType",
    "CommunicationClientType",
    "ComposerType",
    "CreditMessageType",
    "CreditPhase",
    "CustomDatasetType",
    "DataExporterType",
    "DatasetMessageType",
    "EndpointType",
    "ErrorMessageType",
    "ImageFormat",
    "InferenceMessageType",
    "MeasurementMode",
    "MessageType",
    "MetricTimeType",
    "MetricType",
    "Modality",
    "ModelSelectionStrategy",
    "PostProcessorType",
    "ProfileCompletionTrigger",
    "ProfileMessageType",
    "PromptSource",
    "RequestRateMode",
    "ResponsePayloadType",
    "SSEEventType",
    "SSEFieldType",
    "ServiceRegistrationStatus",
    "ServiceRunType",
    "ServiceState",
    "ServiceType",
    "StreamingPostProcessorType",
    "SweepMessageType",
    "SystemMessageType",
    "SystemState",
    "TestMessageType",
    "TimingMode",
    "WorkerMessageType",
    "ZMQProxyType",
]
