#  SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#  SPDX-License-Identifier: Apache-2.0
import abc
from abc import ABC, abstractmethod
from typing import Any

class BasePayloadParser(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    def parse_data_content(self, data_content: list[str]) -> list[str]: ...
    @abstractmethod
    def parse_text_content(self, text_content: str) -> list[str]: ...
    @abstractmethod
    def parse_raw_content(self, raw_content: Any) -> list[str]: ...

class BaseSSEPayloadParser(BasePayloadParser, ABC):
    def parse_text_content(self, text_content: str) -> list[str]: ...
    def parse_data_content(self, data_content: list[str]) -> list[str]: ...
    def parse_raw_content(self, raw_content: Any) -> list[str]: ...
