#  SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#  SPDX-License-Identifier: Apache-2.0
import asyncio
from collections.abc import Callable as Callable
from typing import Protocol

from aiperf.common.hooks import AIPerfHook as AIPerfHook
from aiperf.common.hooks import AIPerfHookParams as AIPerfHookParams
from aiperf.common.hooks import AIPerfTaskHook as AIPerfTaskHook
from aiperf.common.hooks import on_start as on_start
from aiperf.common.hooks import on_stop as on_stop
from aiperf.common.mixins._aiperf_logger import AIPerfLoggerMixin as AIPerfLoggerMixin
from aiperf.common.mixins._async_task_manager import (
    AsyncTaskManagerMixin as AsyncTaskManagerMixin,
)
from aiperf.common.mixins._async_task_manager import (
    AsyncTaskManagerProtocol as AsyncTaskManagerProtocol,
)
from aiperf.common.mixins._hooks import HooksMixin as HooksMixin
from aiperf.common.mixins._hooks import supports_hooks as supports_hooks

class AIPerfLifecycleMixin(HooksMixin, AsyncTaskManagerMixin, AIPerfLoggerMixin):
    initialized_event: asyncio.Event
    started_event: asyncio.Event
    stop_requested: asyncio.Event
    shutdown_event: asyncio.Event
    lifecycle_task: asyncio.Task | None
    def __init__(self, **kwargs) -> None: ...
    def is_initialized(self) -> bool: ...
    async def run_async(self) -> None: ...
    async def run_and_wait_for_start(self) -> None: ...
    async def wait_for_initialize(self) -> None: ...
    async def wait_for_start(self) -> None: ...
    async def wait_for_shutdown(self) -> None: ...
    async def shutdown(self) -> None: ...

class AIPerfLifeCycleProtocol(AsyncTaskManagerProtocol, Protocol):
    def is_initialized(self) -> bool: ...
    async def run_async(self) -> None: ...
    async def run_and_wait_for_start(self) -> None: ...
    async def wait_for_initialize(self) -> None: ...
    async def wait_for_start(self) -> None: ...
    async def wait_for_shutdown(self) -> None: ...
    async def shutdown(self) -> None: ...
