#  SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#  SPDX-License-Identifier: Apache-2.0
import asyncio

from aiperf.common.hooks import AIPerfHook as AIPerfHook
from aiperf.common.messages import Message as Message
from aiperf.common.mixins._aiperf_logger import AIPerfLoggerMixin as AIPerfLoggerMixin
from aiperf.common.mixins._hooks import HooksMixin as HooksMixin
from aiperf.common.mixins._hooks import supports_hooks as supports_hooks

class AIPerfProfileMixin(HooksMixin, AIPerfLoggerMixin):
    profile_started_event: asyncio.Event
    profile_stopped_event: asyncio.Event
    request_profile_stop_event: asyncio.Event
    profile_configured_event: asyncio.Event
    def __init__(self) -> None: ...
    async def configure_profile(self, message: Message): ...
    async def run_profile(self) -> None: ...
    async def stop_profile(self) -> None: ...
    async def wait_for_profile_configured(self) -> None: ...
    async def wait_for_profile_started(self) -> None: ...
    async def wait_for_profile_stopped(self) -> None: ...
