#  SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#  SPDX-License-Identifier: Apache-2.0
from collections.abc import Callable as Callable
from typing import ClassVar

from aiperf.common.hooks import AIPERF_HOOK_TYPE as AIPERF_HOOK_TYPE
from aiperf.common.hooks import HookSystem as HookSystem
from aiperf.common.hooks import HookType as HookType

class HooksMixin:
    supported_hooks: ClassVar[set[HookType]]
    def __init__(self, **kwargs) -> None: ...
    def register_hook(self, hook_type: HookType, func: Callable): ...
    async def run_hooks(self, hook_type: HookType, *args, **kwargs): ...
    async def run_hooks_async(self, hook_type: HookType, *args, **kwargs): ...
    def get_hooks(self, hook_type: HookType) -> list[Callable]: ...

def supports_hooks(*supported_hook_types: HookType) -> Callable[[type], type]: ...
