# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
########################################################################
## mkinit flags                                                       ##
########################################################################
__ignore__ = ["logger"]
__submodules__ = [
    "_base",
    "_credit",
    "_dataset",
    "_error",
    "_health",
    "_record",
    "_service",
    "_worker",
]
########################################################################
## This file is auto-generated by mkinit. Do not edit below this line ##
########################################################################
from aiperf.common.models._base import (
    AIPerfBaseModel,
)
from aiperf.common.models._credit import (
    CreditPhaseConfig,
    CreditPhaseStats,
    PhaseProcessingStats,
)
from aiperf.common.models._dataset import (
    Audio,
    Conversation,
    Image,
    Text,
    Turn,
    TurnInfo,
)
from aiperf.common.models._error import (
    ErrorDetails,
    ErrorDetailsCount,
)
from aiperf.common.models._health import (
    CPUTimes,
    CtxSwitches,
    IOCounters,
    ProcessHealth,
)
from aiperf.common.models._record import (
    InferenceServerResponse,
    MetricResult,
    ParsedResponseRecord,
    RequestRecord,
    ResponseData,
    SSEField,
    SSEMessage,
    TextResponse,
)
from aiperf.common.models._service import (
    ServiceRegistrationInfo,
)
from aiperf.common.models._worker import (
    WorkerPhaseTaskStats,
)

__all__ = [
    "AIPerfBaseModel",
    "Audio",
    "CPUTimes",
    "Conversation",
    "CreditPhaseConfig",
    "CreditPhaseStats",
    "CtxSwitches",
    "ErrorDetails",
    "ErrorDetailsCount",
    "IOCounters",
    "Image",
    "InferenceServerResponse",
    "MetricResult",
    "ParsedResponseRecord",
    "PhaseProcessingStats",
    "ProcessHealth",
    "RequestRecord",
    "ResponseData",
    "SSEField",
    "SSEMessage",
    "ServiceRegistrationInfo",
    "Text",
    "TextResponse",
    "Turn",
    "TurnInfo",
    "WorkerPhaseTaskStats",
]
