#  SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#  SPDX-License-Identifier: Apache-2.0
from typing import Protocol

from aiperf.common.enums import AIPerfUIType as AIPerfUIType
from aiperf.common.factories import FactoryMixin as FactoryMixin
from aiperf.common.messages import Message as Message
from aiperf.progress.progress_tracker import ProgressTracker as ProgressTracker

class AIPerfUIProtocol(Protocol):
    def __init__(self, progress_tracker: ProgressTracker, **kwargs) -> None: ...
    async def on_message(self, message: Message) -> None: ...
    def is_initialized(self) -> bool: ...
    async def run_async(self) -> None: ...
    async def run_and_wait_for_start(self) -> None: ...
    async def wait_for_initialize(self) -> None: ...
    async def wait_for_start(self) -> None: ...
    async def wait_for_shutdown(self) -> None: ...
    async def shutdown(self) -> None: ...

class AIPerfUIFactory(FactoryMixin[AIPerfUIType, AIPerfUIProtocol]): ...
