#  SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#  SPDX-License-Identifier: Apache-2.0
from collections.abc import AsyncIterator, Iterator

from _typeshed import Incomplete

from aiperf.common.messages import WorkerHealthMessage as WorkerHealthMessage

class HealthTracker:
    logger: Incomplete
    worker_health: dict[str, WorkerHealthMessage]
    def __init__(self) -> None: ...
    def __contains__(self, worker_id: str) -> bool: ...
    def __getitem__(self, worker_id: str) -> WorkerHealthMessage: ...
    def __setitem__(self, worker_id: str, health: WorkerHealthMessage) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[tuple[str, WorkerHealthMessage]]: ...
    async def __aiter__(self) -> AsyncIterator[tuple[str, WorkerHealthMessage]]: ...
