# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from typing import Annotated

import cyclopts
from pydantic import Field

from aiperf.common.config.base_config import BaseConfig
from aiperf.common.config.config_defaults import (
    LoadGeneratorDefaults,
    MeasurementDefaults,
)


class LoadGeneratorConfig(BaseConfig):
    """
    A configuration class for defining top-level load generator settings.
    """

    concurrency: Annotated[
        int,
        Field(
            description="The concurrency value to benchmark.",
        ),
    ] = LoadGeneratorDefaults.CONCURRENCY

    request_rate: Annotated[
        float | None,
        Field(
            description="Sets the request rate for the load generated by AIPerf.",
        ),
        cyclopts.Parameter(
            name=("--request-rate"),
        ),
    ] = LoadGeneratorDefaults.REQUEST_RATE

    request_count: Annotated[
        int,
        Field(
            ge=1,
            description="The number of requests to use for measurement.",
        ),
        cyclopts.Parameter(
            name=("--request-count", "--num-requests"),
        ),
    ] = LoadGeneratorDefaults.REQUEST_COUNT

    warmup_request_count: Annotated[
        int,
        Field(
            ge=0,
            description="The number of warmup requests to send before benchmarking.",
        ),
        cyclopts.Parameter(
            name=("--warmup-request-count", "--num-warmup-requests"),
        ),
    ] = LoadGeneratorDefaults.WARMUP_REQUEST_COUNT


class MeasurementConfig(BaseConfig):
    """
    A configuration class for defining top-level measurement settings.
    """

    measurement_interval: Annotated[
        float,
        Field(
            ge=1,
            le=1_000_000,
            description="The time interval used for each measurement in milliseconds. "
            "AIPerf will sample a time interval specified and take "
            "measurement over the requests completed within that time interval. "
            "When using the default stability percentage, AIPerf will benchmark  "
            "for 3*(measurement_interval) milliseconds.",
        ),
        cyclopts.Parameter(
            name=("--measurement-interval", "-p"),
        ),
    ] = MeasurementDefaults.MEASUREMENT_INTERVAL

    stability_percentage: Annotated[
        float,
        Field(
            gt=0.0,
            lt=1.0,
            description="The allowed variation in latency measurements when determining if a result is stable.\n"
            "The measurement is considered as stable if the ratio of max / min\n"
            "from the recent 3 measurements is within (stability percentage)\n"
            "in terms of both infer per second and latency.",
        ),
        cyclopts.Parameter(
            name=("--stability-percentage"),
        ),
    ] = MeasurementDefaults.STABILITY_PERCENTAGE
