#  SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#  SPDX-License-Identifier: Apache-2.0
from dataclasses import dataclass

from aiperf.common.enums import AIPerfLogLevel as AIPerfLogLevel
from aiperf.common.enums import AIPerfUIType as AIPerfUIType
from aiperf.common.enums import AudioFormat as AudioFormat
from aiperf.common.enums import CommunicationBackend as CommunicationBackend
from aiperf.common.enums import CustomDatasetType as CustomDatasetType
from aiperf.common.enums import EndpointType as EndpointType
from aiperf.common.enums import ImageFormat as ImageFormat
from aiperf.common.enums import ModelSelectionStrategy as ModelSelectionStrategy
from aiperf.common.enums import RequestRateMode as RequestRateMode
from aiperf.common.enums import ServiceRunType as ServiceRunType
from aiperf.common.enums import TimingMode as TimingMode

@dataclass(frozen=True)
class UserDefaults:
    MODEL_NAMES = ...

@dataclass(frozen=True)
class CLIDefaults:
    TEMPLATE_FILENAME = ...

@dataclass(frozen=True)
class EndPointDefaults:
    MODEL_SELECTION_STRATEGY = ...
    CUSTOM_ENDPOINT = ...
    TYPE = ...
    STREAMING = ...
    SERVER_METRICS_URLS = ...
    URL = ...
    GRPC_METHOD = ...
    TIMEOUT = ...
    API_KEY = ...

@dataclass(frozen=True)
class InputDefaults:
    BATCH_SIZE = ...
    EXTRA = ...
    GOODPUT = ...
    HEADERS = ...
    FILE = ...
    FIXED_SCHEDULE = ...
    CUSTOM_DATASET_TYPE = ...
    RANDOM_SEED = ...
    NUM_DATASET_ENTRIES = ...

@dataclass(frozen=True)
class AudioDefaults:
    BATCH_SIZE = ...
    LENGTH_MEAN = ...
    LENGTH_STDDEV = ...
    FORMAT = ...
    DEPTHS = ...
    SAMPLE_RATES = ...
    NUM_CHANNELS = ...

@dataclass(frozen=True)
class ImageDefaults:
    BATCH_SIZE = ...
    WIDTH_MEAN = ...
    WIDTH_STDDEV = ...
    HEIGHT_MEAN = ...
    HEIGHT_STDDEV = ...
    FORMAT = ...

@dataclass(frozen=True)
class PromptDefaults:
    BATCH_SIZE = ...

@dataclass(frozen=True)
class InputTokensDefaults:
    MEAN = ...
    STDDEV = ...
    BLOCK_SIZE = ...

@dataclass(frozen=True)
class OutputTokensDefaults:
    MEAN = ...
    DETERMINISTIC = ...
    STDDEV = ...

@dataclass(frozen=True)
class PrefixPromptDefaults:
    POOL_SIZE = ...
    LENGTH = ...

@dataclass(frozen=True)
class ConversationDefaults:
    NUM = ...

@dataclass(frozen=True)
class TurnDefaults:
    MEAN = ...
    STDDEV = ...

@dataclass(frozen=True)
class TurnDelayDefaults:
    MEAN = ...
    STDDEV = ...
    RATIO = ...

@dataclass(frozen=True)
class OutputDefaults:
    ARTIFACT_DIRECTORY = ...
    PROFILE_EXPORT_FILE = ...

@dataclass(frozen=True)
class TokenizerDefaults:
    NAME = ...
    REVISION = ...
    TRUST_REMOTE_CODE = ...

@dataclass(frozen=True)
class OutputTokenDefaults:
    MEAN = ...
    DETERMINISTIC = ...
    STDDEV = ...

@dataclass(frozen=True)
class ServiceDefaults:
    SERVICE_RUN_TYPE = ...
    COMM_BACKEND = ...
    COMM_CONFIG = ...
    HEARTBEAT_TIMEOUT = ...
    REGISTRATION_TIMEOUT = ...
    COMMAND_TIMEOUT = ...
    HEARTBEAT_INTERVAL_SECONDS = ...
    LOG_LEVEL = ...
    VERBOSE = ...
    EXTRA_VERBOSE = ...
    LOG_PATH = ...
    DISABLE_UI = ...
    BASIC_UI = ...
    ENABLE_UVLOOP = ...
    RESULT_PARSER_SERVICE_COUNT = ...
    ENABLE_YAPPI = ...
    DEBUG_SERVICES = ...
    TRACE_SERVICES = ...
    PLUGIN_DIRS = ...
    UI_TYPE = ...
    PROGRESS_REPORT_INTERVAL_SECONDS = ...

@dataclass(frozen=True)
class LoadGeneratorDefaults:
    CONCURRENCY = ...
    REQUEST_RATE = ...
    REQUEST_COUNT = ...
    WARMUP_REQUEST_COUNT = ...
    CONCURRENCY_RAMP_UP_TIME = ...
    REQUEST_RATE_MODE = ...
    TIMING_MODE = ...

@dataclass(frozen=True)
class MeasurementDefaults:
    MEASUREMENT_INTERVAL = ...
    STABILITY_PERCENTAGE = ...

@dataclass(frozen=True)
class WorkerDefaults:
    MIN = ...
    MAX = ...
    HEALTH_CHECK_INTERVAL_SECONDS = ...
