#  SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#  SPDX-License-Identifier: Apache-2.0
from aiperf.common.config._base import BaseConfig as BaseConfig

class SweepParam(BaseConfig): ...
class SweepConfig(BaseConfig): ...
