#  SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#  SPDX-License-Identifier: Apache-2.0
from pathlib import Path
from typing import Any

from aiperf.common.enums import AIPerfUIType as AIPerfUIType
from aiperf.common.enums import ServiceType as ServiceType

def parse_str_or_list(input: Any) -> list[Any]: ...
def parse_str_or_csv_list(input: Any) -> list[Any]: ...
def parse_service_types(input: Any | None) -> set[ServiceType] | None: ...
def parse_str_or_dict(input: Any | None) -> dict[str, Any] | None: ...
def print_str_or_list(input: Any) -> str: ...
def parse_str_or_list_of_positive_values(input: Any) -> list[Any]: ...
def parse_goodput(goodputs: dict[str, Any]) -> dict[str, float]: ...
def parse_file(value: str | None) -> Path | None: ...
def parse_ui_type(input: Any) -> AIPerfUIType: ...
